### ISSUE TITLE
missing mongodb install

### ISSUE THREAD

**Issue by suburbancoder** [mongodb-developer/bakery-workshop#1]
Hi,

I am trying to deploy the docker container from the GCP Lab: Getting Started with MongoDB Atlas on Google Cloud

I am getting the following error during the build:  

src/database.ts(10,24): error TS2304: Cannot find name 'MongoClient'.

----------------------------------------------------------
Full build log below:  

Retrieving builders.
Getting Gcloud Login State.
Using current GCP Project "qwiklabs-gcp-00-2a9e94df0ae6"
Checking Cloud Run API status.
Getting Cloud Run Services for project "qwiklabs-gcp-00-2a9e94df0ae6".
Executing Skaffold build.
Running skaffold command: /usr/bin/skaffold init --artifact {"image":"gcr.io/qwiklabs-gcp-00-2a9e94df0ae6/student-00-6-f-1796-b-62-d-00","builder":"Docker","payload":{"path":"bakery/server/Dockerfile"}} --skip-deploy --filename /tmp/cloud-code-cloud-run-J6k3bE/skaffold.yaml --force
Setting build tagPolicy to SHA256.
Setting statusCheckDeadlineSeconds to 5 minutes
Setting build environment to 'local'
Created the file /tmp/cloud-code-cloud-run-J6k3bE/skaffold.yaml.
Running skaffold command: build --filename /tmp/cloud-code-cloud-run-J6k3bE/skaffold.yaml --kube-context='' --platform=linux/amd64
Generating tags...
 - gcr.io/qwiklabs-gcp-00-2a9e94df0ae6/student-00-6-f-1796-b-62-d-00 ->
gcr.io/qwiklabs-gcp-00-2a9e94df0ae6/student-00-6-f-1796-b-62-d-00:latest
Checking cache...
- gcr.io/qwiklabs-gcp-00-2a9e94df0ae6/student-00-6-f-1796-b-62-d-00: Not found. Building
Starting build...
Building [gcr.io/qwiklabs-gcp-00-2a9e94df0ae6/student-00-6-f-1796-b-62-d-00]...
Target platforms: [linux/amd64]
Sending build context to Docker daemon  62.98kB

Step 1/7 : FROM node:17-slim
17-slim: Pulling from library/node
42c077c10790: Pulling fs layer
1d1b4cabe4ab: Pulling fs layer
fd2a83b16756: Pulling fs layer
cd666498bb13: Pulling fs layer
f428e85c5188: Pulling fs layer
cd666498bb13:
Waiting
f428e85c5188: Waiting
1d1b4cabe4ab: Verifying Checksum
1d1b4cabe4ab: Download complete
cd666498bb13: Verifying Checksum
cd666498bb13: Download complete
42c077c10790: Verifying Checksum
42c077c10790: Download complete
f428e85c5188: Verifying Checksum
f428e85c5188: Download complete
fd2a83b16756: Verifying Checksum
fd2a83b16756: Download complete
42c077c10790: Pull complete
1d1b4cabe4ab: Pull complete
fd2a83b16756: Pull complete
cd666498bb13: Pull complete
f428e85c5188: Pull complete
Digest: sha256:a180966357fe14cac9dd6c9cd496ed4d85b8a598cb33482705ecebad646145e3
Status: Downloaded newer image for node:17-slim
---> af868bc40acd
Step 2/7 : WORKDIR /usr/app
---> Running in 9c36e53e55fe
---> 3cebe5397eac
Step 3/7 : COPY package.json package-lock.json ./
---> ecc8d27827c8
Step 4/7 : RUN npm install

---> Running in d0dafa191934
added 110 packages, and audited 111 packages in 4s

13 packages are looking for funding
  run `npm fund` for details
1 moderate severity vulnerability

To address all issues, run:
  npm audit fix

Run `npm audit` for details.
[91mnpm[0m
[91m [0m[91mnotice[0m
[91m 
[0m
[91mnpm[0m
[91m [0m
[91mnotice[0m
[91m New major version of npm available! 8.11.0 -> 10.8.1
[0m
[91mnpm[0m
[91m [0m
[91mnotice[0m
[91m Changelog: <https://github.com/npm/cli/releases/tag/v10.8.1>
npm notice Run `npm install -g npm@10.8.1` to update!
npm notice 
[0m
---> 140e7f76df2d
Step 5/7 : COPY . .
---> 456da66e598e
Step 6/7 : RUN npm run build
---> Running in a127ff6df9bf
> server@1.0.0 build
> tsc
src/database.ts(10,24): error TS2304: Cannot find name 'MongoClient'.
docker build failure: The command '/bin/sh -c npm run build' returned a non-zero code: 2. Please fix the Dockerfile and try again..
Failed to build the app. Error: docker build failure: The command '/bin/sh -c npm run build' returned a non-zero code: 2. Please fix the Dockerfile and try again..
Executing Skaffold build.

**Comment by sis0k0** [comment]
fixed with https://github.com/mongodb-developer/bakery-workshop/commit/4d88bf3620b6c17c635b251d22ba236ae7f89b11
